### ISSUE TITLE
Errors don't include a valid stack

### ISSUE THREAD

**Issue by benoitvidis** [kuzzleio/sdk-javascript#539]
The stack for errors is taken from kuzzle response, which is in most cases empty, and if not, most likely useless to developers.

A valid stack showing from where the sdk method was called would be nice to have.

**Comment by Aschen** [comment]
I just tried to keep the original stack but since we use the event-emitter mechanism to deal with requests and responses I'm not able to have a meaningful stacktrace :disappointed: 

```
KuzzleError: Caught an unexpected plugin error: some error
This is probably not a Kuzzle error, but a problem with a plugin implementation.
    at Listener.fn (/home/aschen/projets/kuzzleio/sdk-javascript/src/protocols/abstract/Base.js:86:31)
    at HttpProtocol.emit (/home/aschen/projets/kuzzleio/sdk-javascript/src/core/KuzzleEventEmitter.js:97:22)
    at /home/aschen/projets/kuzzleio/sdk-javascript/src/protocols/Http.js:218:36
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 500,
  backendStack: 'Error: some error\n' +
    '    at BaseController.handler [as vault] (/home/aschen/projets/kuzzleio/kuzzle/features-sdk/application/functional-tests-app.ts:95:15)\n' +
    '    at doAction (/home/aschen/projets/kuzzleio/kuzzle/lib/api/funnel.js:748:47)\n' +
    '    at Funnel.processRequest (/home/aschen/projets/kuzzleio/kuzzle/lib/api/funnel.js:414:34)',
  id: 'plugin.runtime.unexpected_error',
  code: 67239938
}
```

**Comment by Aschen** [comment]
To reproduce:

1) clone this branch: https://github.com/kuzzleio/sdk-javascript/tree/539-meaningful-stacktrace

2)  Use this code
```
const { Kuzzle, WebSocket } = require('./index')

const kuzzle = new Kuzzle(new WebSocket('localhost'))

kuzzle.on('networkError', error => console.log(error));

const run = async () => {
  await kuzzle.connect();
  try {
    console.log(await kuzzle.query({
      controller: 'tsts',
      action: 'vault'
    }))
  }
  catch (error) {
    console.log(error)
  }
};

run();
```

3) run it: `node -r ts-node/register test.js`
